### ISSUE TITLE
How to know if a key exists?

### ISSUE THREAD

**Issue by holmes1412** [chanchann/Json#43]
Thanks for this handy Json library 😉

I wonder how to check **if a key exists**? I can't find any APIs in the README, nor in the code by grepping `exist()` or `find()`.

**Comment by chanchann** [comment]
https://github.com/chanchann/Json/blob/56c0e2db0a3282fb3b7be58c08fe2da0de3fd86c/test/json_obj_test.cc#L35

You can call `has()` to check weather the key exists or not.

**Comment by holmes1412** [comment]
🆗
